In [306]:
import pandas as pd
import glob
import re 

csv_files = [f for f in glob.glob("*.csv") 
             if re.match(r'^(201[5-9]|202[0-4])\.csv$', f)]  

dfs = []
for file in csv_files:
    try:
        year = file.split(".")[0]  
        df = pd.read_csv(file)
        df["year"] = int(year) 
        dfs.append(df)
    except Exception as e:
        print(f"Error processing {file}: {e}")


if dfs:
    final_df = pd.concat(dfs, ignore_index=True)

In [307]:
final_df

,Commodity code,Commodity,Trading partner code,Trading partner,US dollar,Unnamed: 5,year
0,203,"Meat of swine, fresh, chilled or frozen",301,Belgium,"47,316",NaN,2020
1,203,"Meat of swine, fresh, chilled or frozen",302,Denmark,"1,081,886,550",NaN,2020
2,203,"Meat of swine, fresh, chilled or frozen",303,United Kingdom,"275,290,010",NaN,2020
3,203,"Meat of swine, fresh, chilled or frozen",304,Germany,"1,272,903,411",NaN,2020
4,203,"Meat of swine, fresh, chilled or frozen",305,France,"368,686,227",NaN,2020
5,203,"Meat of swine, fresh, chilled or frozen",306,Ireland,"173,166,564",NaN,2020
6,203,"Meat of swine, fresh, chilled or frozen",307,Italy,"54,251,877",NaN,2020
7,203,"Meat of swine, fresh, chilled or frozen",309,Netherlands,"762,867,775",NaN,2020
8,203,"Meat of swine, fresh, chilled or frozen",311,Portugal,"59,939,512",NaN,2020
9,203,"Meat of swine, fresh, chilled or frozen",312,Spain,"2,673,665,706",NaN,2020
10,203,"Meat of swine, fresh, chilled or frozen",315,Austria,"117,502,432",NaN,2020
11,203,"Meat of swine, fresh, chilled or frozen",318,Finland,"51,833,056",NaN,2020
12,203,"Meat of swine, fresh, chilled or frozen",331,Switzerland,"2,360,754",NaN,2020
13,203,"Meat of swine, fresh, chilled or frozen",402,Argentina,"54,501,947",NaN,2020
14,203,"Meat of swine, fresh, chilled or frozen",410,Brazil,"1,563,862,718",NaN,2020
15,203,"Meat of swine, fresh, chilled or frozen",412,Chile,"471,563,604",NaN,2020
16,203,"Meat of swine, fresh, chilled or frozen",415,Costa Rica,"6,122,143",NaN,2020
17,203,"Meat of swine, fresh, chilled or frozen",429,Mexico,"279,385,400",NaN,2020
18,203,"Meat of swine, fresh, chilled or frozen",501,Canada,"972,141,323",NaN,2020
19,203,"Meat of swine, fresh, chilled or frozen",502,United States,"1,636,402,174",NaN,2020
20,203,"Meat of swine, fresh, chilled or frozen",302,Denmark,"959,619,160",NaN,2021
21,203,"Meat of swine, fresh, chilled or frozen",303,United Kingdom,"252,457,590",NaN,2021
22,203,"Meat of swine, fresh, chilled or frozen",304,Germany,"7,055,511",NaN,2021
23,203,"Meat of swine, fresh, chilled or frozen",305,France,"454,960,966",NaN,2021
24,203,"Meat of swine, fresh, chilled or frozen",306,Ireland,"185,988,455",NaN,2021
25,203,"Meat of swine, fresh, chilled or frozen",307,Italy,"89,856,900",NaN,2021
26,203,"Meat of swine, fresh, chilled or frozen",309,Netherlands,"769,871,002",NaN,2021
27,203,"Meat of swine, fresh, chilled or frozen",311,Portugal,"63,535,390",NaN,2021
28,203,"Meat of swine, fresh, chilled or frozen",312,Spain,"3,131,143,632",NaN,2021
29,203,"Meat of swine, fresh, chilled or frozen",315,Austria,"123,718,275",NaN,2021
30,203,"Meat of swine, fresh, chilled or frozen",318,Finland,"50,220,970",NaN,2021
31,203,"Meat of swine, fresh, chilled or frozen",331,Switzerland,"3,481,577",NaN,2021
32,203,"Meat of swine, fresh, chilled or frozen",402,Argentina,"54,280,837",NaN,2021
33,203,"Meat of swine, fresh, chilled or frozen",410,Brazil,"1,655,381,911",NaN,2021
34,203,"Meat of swine, fresh, chilled or frozen",412,Chile,"371,840,602",NaN,2021
35,203,"Meat of swine, fresh, chilled or frozen",415,Costa Rica,"424,258",NaN,2021
36,203,"Meat of swine, fresh, chilled or frozen",429,Mexico,"181,116,765",NaN,2021
37,203,"Meat of swine, fresh, chilled or frozen",501,Canada,"608,929,219",NaN,2021
38,203,"Meat of swine, fresh, chilled or frozen",502,United States,"921,030,930",NaN,2021
39,203,"Meat of swine, fresh, chilled or frozen",302,Denmark,"288,890,249",NaN,2023
40,203,"Meat of swine, fresh, chilled or frozen",303,United Kingdom,"130,505,440",NaN,2023
41,203,"Meat of swine, fresh, chilled or frozen",305,France,"152,839,218",NaN,2023
42,203,"Meat of swine, fresh, chilled or frozen",306,Ireland,"71,901,939",NaN,2023
43,203,"Meat of swine, fresh, chilled or frozen",309,Netherlands,"267,277,430",NaN,2023
44,203,"Meat of swine, fresh, chilled or frozen",311,Portugal,"6,636,566",NaN,2023
45,203,"Meat of swine, fresh, chilled or frozen",312,Spain,"865,296,368",NaN,2023
46,203,"Meat of swine, fresh, chilled or frozen",315,Austria,"30,152,602",NaN,2023
47,203,"Meat of swine, fresh, chilled or frozen",318,Finland,"10,702,115",NaN,2023
48,203,"Meat of swine, fresh, chilled or frozen",331,Switzerland,"2,406,790",NaN,2023
49,203,"Meat of swine, fresh, chilled or frozen",402,Argentina,"947,716",NaN,2023
50,203,"Meat of swine, fresh, chilled or frozen",410,Brazil,"998,682,654",NaN,2023
51,203,"Meat of swine, fresh, chilled or frozen",412,Chile,"162,679,996",NaN,2023
52,203,"Meat of swine, fresh, chilled or frozen",429,Mexico,"5,927,048",NaN,2023
53,203,"Meat of swine, fresh, chilled or frozen",501,Canada,"271,064,474",NaN,2023
54,203,"Meat of swine, fresh, chilled or frozen",502,United States,"217,881,049",NaN,2023
55,203,"Meat of swine, fresh, chilled or frozen",302,Denmark,"444,349,360",NaN,2022
56,203,"Meat of swine, fresh, chilled or frozen",303,United Kingdom,"146,219,259",NaN,2022
57,203,"Meat of swine, fresh, chilled or frozen",305,France,"153,315,470",NaN,2022
58,203,"Meat of swine, fresh, chilled or frozen",306,Ireland,"78,657,443",NaN,2022
59,203,"Meat of swine, fresh, chilled or frozen",307,Italy,"5,637,526",NaN,2022
60,203,"Meat of swine, fresh, chilled or frozen",309,Netherlands,"265,232,488",NaN,2022
61,203,"Meat of swine, fresh, chilled or frozen",311,Portugal,"9,456,618",NaN,2022
62,203,"Meat of swine, fresh, chilled or frozen",312,Spain,"1,068,645,582",NaN,2022
63,203,"Meat of swine, fresh, chilled or frozen",315,Austria,"32,859,649",NaN,2022
64,203,"Meat of swine, fresh, chilled or frozen",318,Finland,"12,288,220",NaN,2022
65,203,"Meat of swine, fresh, chilled or frozen",331,Switzerland,"2,940,224",NaN,2022
66,203,"Meat of swine, fresh, chilled or frozen",402,Argentina,"229,780",NaN,2022
67,203,"Meat of swine, fresh, chilled or frozen",410,Brazil,"995,055,614",NaN,2022
68,203,"Meat of swine, fresh, chilled or frozen",412,Chile,"141,963,515",NaN,2022
69,203,"Meat of swine, fresh, chilled or frozen",415,Costa Rica,"59,938",NaN,2022
70,203,"Meat of swine, fresh, chilled or frozen",429,Mexico,"34,481,792",NaN,2022
71,203,"Meat of swine, fresh, chilled or frozen",501,Canada,"233,944,545",NaN,2022
72,203,"Meat of swine, fresh, chilled or frozen",502,United States,"212,475,484",NaN,2022
73,203,"Meat of swine, fresh, chilled or frozen",302,Denmark,"425,353,816",NaN,2019
74,203,"Meat of swine, fresh, chilled or frozen",303,United Kingdom,"142,619,822",NaN,2019
75,203,"Meat of swine, fresh, chilled or frozen",304,Germany,"668,873,740",NaN,2019
76,203,"Meat of swine, fresh, chilled or frozen",305,France,"197,398,309",NaN,2019
77,203,"Meat of swine, fresh, chilled or frozen",306,Ireland,"113,504,149",NaN,2019
78,203,"Meat of swine, fresh, chilled or frozen",307,Italy,"6,813",NaN,2019
79,203,"Meat of swine, fresh, chilled or frozen",309,Netherlands,"363,154,414",NaN,2019
80,203,"Meat of swine, fresh, chilled or frozen",311,Portugal,"7,629,334",NaN,2019
81,203,"Meat of swine, fresh, chilled or frozen",312,Spain,"907,925,453",NaN,2019
82,203,"Meat of swine, fresh, chilled or frozen",315,Austria,"20,970,694",NaN,2019
83,203,"Meat of swine, fresh, chilled or frozen",318,Finland,"11,969,841",NaN,2019
84,203,"Meat of swine, fresh, chilled or frozen",402,Argentina,"3,035,604",NaN,2019
85,203,"Meat of swine, fresh, chilled or frozen",410,Brazil,"606,545,872",NaN,2019
86,203,"Meat of swine, fresh, chilled or frozen",412,Chile,"177,814,782",NaN,2019
87,203,"Meat of swine, fresh, chilled or frozen",429,Mexico,"37,457,411",NaN,2019
88,203,"Meat of swine, fresh, chilled or frozen",501,Canada,"317,730,938",NaN,2019
89,203,"Meat of swine, fresh, chilled or frozen",502,United States,"506,521,958",NaN,2019
90,203,NaN,301,Belgium,"7,712,990",NaN,2018
91,203,NaN,302,Denmark,"140,373,605",NaN,2018
92,203,NaN,303,United Kingdom,"68,965,811",NaN,2018
93,203,NaN,304,Germany,"392,021,892",NaN,2018
94,203,NaN,305,France,"105,312,445",NaN,2018
95,203,NaN,306,Ireland,"55,576,638",NaN,2018
96,203,NaN,307,Italy,"16,758",NaN,2018
97,203,NaN,309,Netherlands,"145,353,373",NaN,2018
98,203,NaN,312,Spain,"384,960,228",NaN,2018
99,203,NaN,315,Austria,"1,598,973",NaN,2018
100,203,NaN,318,Finland,"2,869,922",NaN,2018
101,203,NaN,321,Hungary,"11,948,389",NaN,2018
102,203,NaN,334,Estonia,878,NaN,2018
103,203,NaN,336,Lithuania,875,NaN,2018
104,203,NaN,410,Brazil,"317,338,280",NaN,2018
105,203,NaN,412,Chile,"58,615,459",NaN,2018
106,203,NaN,429,Mexico,"2,608,123",NaN,2018
107,203,NaN,501,Canada,"249,307,186",NaN,2018
108,203,NaN,502,United States,"129,403,880",NaN,2018
109,203,"Meat of swine, fresh, chilled or frozen",301,Belgium,"2,832,568",NaN,2024
110,203,"Meat of swine, fresh, chilled or frozen",302,Denmark,"123,593,769",NaN,2024
111,203,"Meat of swine, fresh, chilled or frozen",303,United Kingdom,"100,540,174",NaN,2024
112,203,"Meat of swine, fresh, chilled or frozen",305,France,"104,698,680",NaN,2024
113,203,"Meat of swine, fresh, chilled or frozen",306,Ireland,"54,374,966",NaN,2024
114,203,"Meat of swine, fresh, chilled or frozen",309,Netherlands,"140,435,585",NaN,2024
115,203,"Meat of swine, fresh, chilled or frozen",311,Portugal,"4,129,969",NaN,2024
116,203,"Meat of swine, fresh, chilled or frozen",312,Spain,"606,127,713",NaN,2024
117,203,"Meat of swine, fresh, chilled or frozen",315,Austria,"13,598,553",NaN,2024
118,203,"Meat of swine, fresh, chilled or frozen",318,Finland,"5,820,591",NaN,2024
119,203,"Meat of swine, fresh, chilled or frozen",331,Switzerland,"1,297,297",NaN,2024
120,203,"Meat of swine, fresh, chilled or frozen",344,Russia,"53,305,738",NaN,2024
121,203,"Meat of swine, fresh, chilled or frozen",402,Argentina,"2,666,239",NaN,2024
122,203,"Meat of swine, fresh, chilled or frozen",410,Brazil,"533,147,875",NaN,2024
123,203,"Meat of swine, fresh, chilled or frozen",412,Chile,"104,570,171",NaN,2024
124,203,"Meat of swine, fresh, chilled or frozen",429,Mexico,"222,162",NaN,2024
125,203,"Meat of swine, fresh, chilled or frozen",501,Canada,"123,867,367",NaN,2024
126,203,"Meat of swine, fresh, chilled or frozen",502,United States,"119,607,784",NaN,2024
127,203,"Meat of swine, fresh, chilled or frozen",301,Belgium,"21,681,409",NaN,2016
128,203,"Meat of swine, fresh, chilled or frozen",302,Denmark,"333,893,555",NaN,2016
129,203,"Meat of swine, fresh, chilled or frozen",303,United Kingdom,"68,318,689",NaN,2016
130,203,"Meat of swine, fresh, chilled or frozen",304,Germany,"665,751,253",NaN,2016
131,203,"Meat of swine, fresh, chilled or frozen",305,France,"188,832,716",NaN,2016
132,203,"Meat of swine, fresh, chilled or frozen",306,Ireland,"87,217,949",NaN,2016
133,203,"Meat of swine, fresh, chilled or frozen",309,Netherlands,"235,807,055",NaN,2016
134,203,"Meat of swine, fresh, chilled or frozen",312,Spain,"520,118,603",NaN,2016
135,203,"Meat of swine, fresh, chilled or frozen",321,Hungary,"49,679,524",NaN,2016
136,203,"Meat of swine, fresh, chilled or frozen",328,Romania,"8,715,708",NaN,2016
137,203,"Meat of swine, fresh, chilled or frozen",350,Slovenia,"414,720",NaN,2016
138,203,"Meat of swine, fresh, chilled or frozen",410,Brazil,"192,860,954",NaN,2016
139,203,"Meat of swine, fresh, chilled or frozen",412,Chile,"87,234,186",NaN,2016
140,203,"Meat of swine, fresh, chilled or frozen",429,Mexico,"285,784",NaN,2016
141,203,"Meat of swine, fresh, chilled or frozen",501,Canada,"320,392,179",NaN,2016
142,203,"Meat of swine, fresh, chilled or frozen",502,United States,"409,214,863",NaN,2016
143,203,NaN,301,Belgium,"13,204,631",NaN,2017
144,203,NaN,302,Denmark,"181,898,775",NaN,2017
145,203,NaN,303,United Kingdom,"64,997,690",NaN,2017
146,203,NaN,304,Germany,"392,719,136",NaN,2017
147,203,NaN,305,France,"116,008,824",NaN,2017
148,203,NaN,306,Ireland,"66,492,899",NaN,2017
149,203,NaN,309,Netherlands,"156,450,430",NaN,2017
150,203,NaN,312,Spain,"439,857,962",NaN,2017
151,203,NaN,318,Finland,"1,462,402",NaN,2017
152,203,NaN,321,Hungary,"44,168,096",NaN,2017
153,203,NaN,328,Romania,"6,573,102",NaN,2017
154,203,NaN,410,Brazil,"112,502,038",NaN,2017
155,203,NaN,412,Chile,"63,060,033",NaN,2017
156,203,NaN,429,Mexico,"2,071,426",NaN,2017
157,203,NaN,501,Canada,"273,501,799",NaN,2017
158,203,NaN,502,United States,"285,678,683",NaN,2017
159,203,NaN,609,New Zealand,"31,057",NaN,2017

In [308]:
final_df.groupby('year')['Trading partner'].count()

year
2016    16
2017    17
2018    19
2019    17
2020    20
2021    19
2022    18
2023    16
2024    18
Name: Trading partner, dtype: int64

In [309]:
grouped = final_df.groupby(['year', 'Trading partner'])['US dollar'].sum().reset_index()

grouped

     year Trading partner      US dollar
0    2016         Belgium     21,681,409
1    2016          Brazil    192,860,954
2    2016          Canada    320,392,179
3    2016           Chile     87,234,186
4    2016         Denmark    333,893,555
5    2016          France    188,832,716
6    2016         Germany    665,751,253
7    2016         Hungary     49,679,524
8    2016         Ireland     87,217,949
9    2016          Mexico        285,784
10   2016     Netherlands    235,807,055
11   2016         Romania      8,715,708
12   2016        Slovenia        414,720
13   2016           Spain    520,118,603
14   2016  United Kingdom     68,318,689
15   2016   United States    409,214,863
16   2017         Belgium     13,204,631
17   2017          Brazil    112,502,038
18   2017          Canada    273,501,799
19   2017           Chile     63,060,033
20   2017         Denmark    181,898,775
21   2017         Finland      1,462,402
22   2017          France    116,008,824
23   2017         Germany    392,719,136
24   2017         Hungary     44,168,096
25   2017         Ireland     66,492,899
26   2017          Mexico      2,071,426
27   2017     Netherlands    156,450,430
28   2017     New Zealand         31,057
29   2017         Romania      6,573,102
30   2017           Spain    439,857,962
31   2017  United Kingdom     64,997,690
32   2017   United States    285,678,683
33   2018         Austria      1,598,973
34   2018         Belgium      7,712,990
35   2018          Brazil    317,338,280
36   2018          Canada    249,307,186
37   2018           Chile     58,615,459
38   2018         Denmark    140,373,605
39   2018         Estonia            878
40   2018         Finland      2,869,922
41   2018          France    105,312,445
42   2018         Germany    392,021,892
43   2018         Hungary     11,948,389
44   2018         Ireland     55,576,638
45   2018           Italy         16,758
46   2018       Lithuania            875
47   2018          Mexico      2,608,123
48   2018     Netherlands    145,353,373
49   2018           Spain    384,960,228
50   2018  United Kingdom     68,965,811
51   2018   United States    129,403,880
52   2019       Argentina      3,035,604
53   2019         Austria     20,970,694
54   2019          Brazil    606,545,872
55   2019          Canada    317,730,938
56   2019           Chile    177,814,782
57   2019         Denmark    425,353,816
58   2019         Finland     11,969,841
59   2019          France    197,398,309
60   2019         Germany    668,873,740
61   2019         Ireland    113,504,149
62   2019           Italy          6,813
63   2019          Mexico     37,457,411
64   2019     Netherlands    363,154,414
65   2019        Portugal      7,629,334
66   2019           Spain    907,925,453
67   2019  United Kingdom    142,619,822
68   2019   United States    506,521,958
69   2020       Argentina     54,501,947
70   2020         Austria    117,502,432
71   2020         Belgium         47,316
72   2020          Brazil  1,563,862,718
73   2020          Canada    972,141,323
74   2020           Chile    471,563,604
75   2020      Costa Rica      6,122,143
76   2020         Denmark  1,081,886,550
77   2020         Finland     51,833,056
78   2020          France    368,686,227
79   2020         Germany  1,272,903,411
80   2020         Ireland    173,166,564
81   2020           Italy     54,251,877
82   2020          Mexico    279,385,400
83   2020     Netherlands    762,867,775
84   2020        Portugal     59,939,512
85   2020           Spain  2,673,665,706
86   2020     Switzerland      2,360,754
87   2020  United Kingdom    275,290,010
88   2020   United States  1,636,402,174
89   2021       Argentina     54,280,837
90   2021         Austria    123,718,275
91   2021          Brazil  1,655,381,911
92   2021          Canada    608,929,219
93   2021           Chile    371,840,602
94   2021      Costa Rica        424,258
95   2021         Denmark    959,619,160
96   2021         Finland     50,220,970
97   2021          France    454,960,966
98   2021         Germany      7,055,511
99   2021         Ireland    185,988,455
100  2021           Italy     89,856,900
101  2021          Mexico    181,116,765
102  2021     Netherlands    769,871,002
103  2021        Portugal     63,535,390
104  2021           Spain  3,131,143,632
105  2021     Switzerland      3,481,577
106  2021  United Kingdom    252,457,590
107  2021   United States    921,030,930
108  2022       Argentina        229,780
109  2022         Austria     32,859,649
110  2022          Brazil    995,055,614
111  2022          Canada    233,944,545
112  2022           Chile    141,963,515
113  2022      Costa Rica         59,938
114  2022         Denmark    444,349,360
115  2022         Finland     12,288,220
116  2022          France    153,315,470
117  2022         Ireland     78,657,443
118  2022           Italy      5,637,526
119  2022          Mexico     34,481,792
120  2022     Netherlands    265,232,488
121  2022        Portugal      9,456,618
122  2022           Spain  1,068,645,582
123  2022     Switzerland      2,940,224
124  2022  United Kingdom    146,219,259
125  2022   United States    212,475,484
126  2023       Argentina        947,716
127  2023         Austria     30,152,602
128  2023          Brazil    998,682,654
129  2023          Canada    271,064,474
130  2023           Chile    162,679,996
131  2023         Denmark    288,890,249
132  2023         Finland     10,702,115
133  2023          France    152,839,218
134  2023         Ireland     71,901,939
135  2023          Mexico      5,927,048
136  2023     Netherlands    267,277,430
137  2023        Portugal      6,636,566
138  2023           Spain    865,296,368
139  2023     Switzerland      2,406,790
140  2023  United Kingdom    130,505,440
141  2023   United States    217,881,049
142  2024       Argentina      2,666,239
143  2024         Austria     13,598,553
144  2024         Belgium      2,832,568
145  2024          Brazil    533,147,875
146  2024          Canada    123,867,367
147  2024           Chile    104,570,171
148  2024         Denmark    123,593,769
149  2024         Finland      5,820,591
150  2024          France    104,698,680
151  2024         Ireland     54,374,966
152  2024          Mexico        222,162
153  2024     Netherlands    140,435,585
154  2024        Portugal      4,129,969
155  2024          Russia     53,305,738
156  2024           Spain    606,127,713
157  2024     Switzerland      1,297,297
158  2024  United Kingdom    100,540,174
159  2024   United States    119,607,784

In [310]:
grouped['US dollar'] = grouped['US dollar'].str.replace(',', '').astype(float)

# 2. Pivot the table (countries as rows, years as columns)
pivoted = grouped.pivot(index='Trading partner',
                   columns='year',
                   values='US dollar')

# 3. Convert to billions and round to 3 decimals
pivoted = (pivoted / 1e9).round(3)

# 4. Add Grand Total row
pivoted.loc['GRAND TOTAL'] = pivoted.sum()

# 5. Sort countries alphabetically (optional)
pivoted = pivoted.sort_index()

# 6. Clean up presentation
final_df = pivoted.reset_index()
final_df = final_df.rename_axis(None, axis=1)  # Remove column axis name

In [325]:
final_df

,Trading partner,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Argentina,NaN,NaN,NaN,0.003,0.055,0.054,0.000,0.001,0.003
1,Austria,NaN,NaN,0.002,0.021,0.118,0.124,0.033,0.030,0.014
2,Belgium,0.022,0.013,0.008,NaN,0.000,NaN,NaN,NaN,0.003
3,Brazil,0.193,0.113,0.317,0.607,1.564,1.655,0.995,0.999,0.533
4,Canada,0.320,0.274,0.249,0.318,0.972,0.609,0.234,0.271,0.124
5,Chile,0.087,0.063,0.059,0.178,0.472,0.372,0.142,0.163,0.105
6,Costa Rica,NaN,NaN,NaN,NaN,0.006,0.000,0.000,NaN,NaN
7,Denmark,0.334,0.182,0.140,0.425,1.082,0.960,0.444,0.289,0.124
8,Estonia,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN
9,Finland,NaN,0.001,0.003,0.012,0.052,0.050,0.012,0.011,0.006
10,France,0.189,0.116,0.105,0.197,0.369,0.455,0.153,0.153,0.105
11,GRAND TOTAL,3.190,2.221,2.074,4.510,11.879,9.884,3.836,3.485,2.096
12,Germany,0.666,0.393,0.392,0.669,1.273,0.007,NaN,NaN,NaN
13,Hungary,0.050,0.044,0.012,NaN,NaN,NaN,NaN,NaN,NaN
14,Ireland,0.087,0.066,0.056,0.114,0.173,0.186,0.079,0.072,0.054
15,Italy,NaN,NaN,0.000,0.000,0.054,0.090,0.006,NaN,NaN
16,Lithuania,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN
17,Mexico,0.000,0.002,0.003,0.037,0.279,0.181,0.034,0.006,0.000
18,Netherlands,0.236,0.156,0.145,0.363,0.763,0.770,0.265,0.267,0.140
19,New Zealand,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Portugal,NaN,NaN,NaN,0.008,0.060,0.064,0.009,0.007,0.004
21,Romania,0.009,0.007,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Russia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.053
23,Slovenia,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Spain,0.520,0.440,0.385,0.908,2.674,3.131,1.069,0.865,0.606
25,Switzerland,NaN,NaN,NaN,NaN,0.002,0.003,0.003,0.002,0.001
26,United Kingdom,0.068,0.065,0.069,0.143,0.275,0.252,0.146,0.131,0.101
27,United States,0.409,0.286,0.129,0.507,1.636,0.921,0.212,0.218,0.120

In [326]:
selected_countries = ['United States', 'Spain', 'Brazil']

# Filter rows (including GRAND TOTAL)
filtered_df = final_df[
    final_df['Trading partner'].isin(selected_countries + ['GRAND TOTAL'])]

In [327]:
filtered_df

,Trading partner,2016,2017,2018,2019,2020,2021,2022,2023,2024
3,Brazil,0.193,0.113,0.317,0.607,1.564,1.655,0.995,0.999,0.533
11,GRAND TOTAL,3.190,2.221,2.074,4.510,11.879,9.884,3.836,3.485,2.096
24,Spain,0.520,0.440,0.385,0.908,2.674,3.131,1.069,0.865,0.606
27,United States,0.409,0.286,0.129,0.507,1.636,0.921,0.212,0.218,0.120

In [323]:
# Step 1: Calculate grand total (sum of all rows)
grand_total = grouped.sum(numeric_only=True)

# Step 2: Calculate the sum of the selected 5 countries
selected_sum = filtered_df.sum(numeric_only=True)

# Step 3: Calculate the difference
rest_sum = grand_total - selected_sum

# Step 4: Create a new row for "Rest of the World"
rest_row = pd.DataFrame([rest_sum], index=['Rest of the World'])

# Step 5: Add a 'Trading partner' column
rest_row['Trading partner'] = 'Rest of the World'

# Step 6: Combine with original result
final_result = pd.concat([filtered_df, rest_row], ignore_index=True)

In [324]:
final_result

,Trading partner,2016,2017,2018,2019,2020,2021,2022,2023,2024,US dollar,year
0,Brazil,0.193,0.113,0.317,0.607,1.564,1.655,0.995,0.999,0.533,NaN,NaN
1,Canada,0.320,0.274,0.249,0.318,0.972,0.609,0.234,0.271,0.124,NaN,NaN
2,Denmark,0.334,0.182,0.140,0.425,1.082,0.960,0.444,0.289,0.124,NaN,NaN
3,GRAND TOTAL,3.190,2.221,2.074,4.510,11.879,9.884,3.836,3.485,2.096,NaN,NaN
4,Spain,0.520,0.440,0.385,0.908,2.674,3.131,1.069,0.865,0.606,NaN,NaN
5,United States,0.409,0.286,0.129,0.507,1.636,0.921,0.212,0.218,0.120,NaN,NaN
6,Rest of the World,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [295]:
result = grouped[grouped['Trading partner'].isin(['Spain', 'United States', 'Brazil', 'Denmark', 'Canada'])]

result

     year Trading partner     US dollar
1    2016          Brazil  1.928610e+08
2    2016          Canada  3.203922e+08
4    2016         Denmark  3.338936e+08
13   2016           Spain  5.201186e+08
15   2016   United States  4.092149e+08
17   2017          Brazil  1.125020e+08
18   2017          Canada  2.735018e+08
20   2017         Denmark  1.818988e+08
30   2017           Spain  4.398580e+08
32   2017   United States  2.856787e+08
35   2018          Brazil  3.173383e+08
36   2018          Canada  2.493072e+08
38   2018         Denmark  1.403736e+08
49   2018           Spain  3.849602e+08
51   2018   United States  1.294039e+08
54   2019          Brazil  6.065459e+08
55   2019          Canada  3.177309e+08
57   2019         Denmark  4.253538e+08
66   2019           Spain  9.079255e+08
68   2019   United States  5.065220e+08
72   2020          Brazil  1.563863e+09
73   2020          Canada  9.721413e+08
76   2020         Denmark  1.081887e+09
85   2020           Spain  2.673666e+09
88   2020   United States  1.636402e+09
91   2021          Brazil  1.655382e+09
92   2021          Canada  6.089292e+08
95   2021         Denmark  9.596192e+08
104  2021           Spain  3.131144e+09
107  2021   United States  9.210309e+08
110  2022          Brazil  9.950556e+08
111  2022          Canada  2.339445e+08
114  2022         Denmark  4.443494e+08
122  2022           Spain  1.068646e+09
125  2022   United States  2.124755e+08
128  2023          Brazil  9.986827e+08
129  2023          Canada  2.710645e+08
131  2023         Denmark  2.888902e+08
138  2023           Spain  8.652964e+08
141  2023   United States  2.178810e+08
145  2024          Brazil  5.331479e+08
146  2024          Canada  1.238674e+08
148  2024         Denmark  1.235938e+08
156  2024           Spain  6.061277e+08
159  2024   United States  1.196078e+08

# Offals

In [233]:
import os

offals_path = os.path.join('offals', 'of_*.csv')


all_dfs = []

for file_path in glob.glob(offals_path):
    try:
        year = 2000 + int(re.search(r'of_(\d{2})\.csv', file_path).group(1))
        
        for encoding in ['utf-8', 'latin1', 'cp1252']:
            try:
                df = pd.read_csv(file_path, encoding=encoding)
                df['year'] = year  # Add year column
                all_dfs.append(df)
                print(f"✓ Successfully read {os.path.basename(file_path)} with {encoding} encoding")
                break
            except UnicodeDecodeError:
                continue
    
    except Exception as e:
        print(f"⚠️ Failed to process {os.path.basename(file_path)}: {str(e)}")
        continue

if all_dfs:
    combined_df = pd.concat(all_dfs, ignore_index=True)

else:
    print("No files were processed successfully")

✓ Successfully read of_17.csv with latin1 encoding
✓ Successfully read of_16.csv with latin1 encoding
✓ Successfully read of_24.csv with utf-8 encoding
✓ Successfully read of_18.csv with latin1 encoding
✓ Successfully read of_19.csv with utf-8 encoding
✓ Successfully read of_22.csv with utf-8 encoding
✓ Successfully read of_23.csv with utf-8 encoding
✓ Successfully read of_21.csv with utf-8 encoding
✓ Successfully read of_20.csv with utf-8 encoding

In [234]:
combined_df

,Commodity code,Commodity,Trading partner code,Trading partner,US dollar,Unnamed: 5,year
0,20641,NaN,302,Denmark,"65,538",NaN,2017
1,20641,NaN,303,United Kingdom,"14,227",NaN,2017
2,20641,NaN,305,France,"1,041",NaN,2017
3,20641,NaN,312,Spain,"179,412",NaN,2017
4,20641,NaN,501,Canada,"60,947",NaN,2017
5,20649,NaN,301,Belgium,"25,579,786",NaN,2017
6,20649,NaN,302,Denmark,"219,860,769",NaN,2017
7,20649,NaN,303,United Kingdom,"31,015,194",NaN,2017
8,20649,NaN,304,Germany,"213,418,028",NaN,2017
9,20649,NaN,305,France,"114,278,634",NaN,2017
10,20649,NaN,306,Ireland,"32,371,683",NaN,2017
11,20649,NaN,309,Netherlands,"154,377,740",NaN,2017
12,20649,NaN,312,Spain,"198,157,822",NaN,2017
13,20649,NaN,318,Finland,"1,825,322",NaN,2017
14,20649,NaN,321,Hungary,"18,168,581",NaN,2017
15,20649,NaN,328,Romania,"7,439,128",NaN,2017
16,20649,NaN,412,Chile,"37,486,297",NaN,2017
17,20649,NaN,429,Mexico,"1,110,387",NaN,2017
18,20649,NaN,501,Canada,"183,908,134",NaN,2017
19,20649,NaN,502,United States,"873,810,968",NaN,2017
20,160249,NaN,116,Japan,54,NaN,2017
21,160249,NaN,133,Republic of Korea,918,NaN,2017
22,160249,NaN,136,Thailand,"2,065",NaN,2017
23,160249,NaN,142,China,"937,027",NaN,2017
24,160249,NaN,143,Taiwan£¬China,"5,170",NaN,2017
25,160249,NaN,305,France,437,NaN,2017
26,160249,NaN,307,Italy,"38,642",NaN,2017
27,160249,NaN,312,Spain,"32,771",NaN,2017
28,160249,NaN,354,North Macedonia,1,NaN,2017
29,160249,NaN,501,Canada,42,NaN,2017
30,20641,"Livers,frozen",301,Belgium,"19,375",NaN,2016
31,20641,"Livers,frozen",302,Denmark,"707,324",NaN,2016
32,20641,"Livers,frozen",303,United Kingdom,"603,847",NaN,2016
33,20641,"Livers,frozen",304,Germany,"1,554,026",NaN,2016
34,20641,"Livers,frozen",305,France,"227,606",NaN,2016
35,20641,"Livers,frozen",306,Ireland,"489,896",NaN,2016
36,20641,"Livers,frozen",309,Netherlands,"1,680,348",NaN,2016
37,20641,"Livers,frozen",312,Spain,"1,824,212",NaN,2016
38,20641,"Livers,frozen",321,Hungary,"44,925",NaN,2016
39,20641,"Livers,frozen",328,Romania,"131,168",NaN,2016
40,20641,"Livers,frozen",412,Chile,"594,559",NaN,2016
41,20641,"Livers,frozen",501,Canada,"1,785,049",NaN,2016
42,20649,"Other edible offal of swine,frozen",301,Belgium,"26,771,426",NaN,2016
43,20649,"Other edible offal of swine,frozen",302,Denmark,"337,105,813",NaN,2016
44,20649,"Other edible offal of swine,frozen",303,United Kingdom,"36,704,897",NaN,2016
45,20649,"Other edible offal of swine,frozen",304,Germany,"359,101,656",NaN,2016
46,20649,"Other edible offal of swine,frozen",305,France,"116,069,557",NaN,2016
47,20649,"Other edible offal of swine,frozen",306,Ireland,"34,794,462",NaN,2016
48,20649,"Other edible offal of swine,frozen",309,Netherlands,"154,456,370",NaN,2016
49,20649,"Other edible offal of swine,frozen",312,Spain,"180,383,442",NaN,2016
50,20649,"Other edible offal of swine,frozen",321,Hungary,"18,332,530",NaN,2016
51,20649,"Other edible offal of swine,frozen",328,Romania,"4,353,897",NaN,2016
52,20649,"Other edible offal of swine,frozen",412,Chile,"43,506,533",NaN,2016
53,20649,"Other edible offal of swine,frozen",429,Mexico,"89,570",NaN,2016
54,20649,"Other edible offal of swine,frozen",501,Canada,"198,489,963",NaN,2016
55,20649,"Other edible offal of swine,frozen",502,United States,"936,811,145",NaN,2016
56,160249,Other prepared or preserved meat and meat offa...,110,Hong Kong£¬China,831,NaN,2016
57,160249,Other prepared or preserved meat and meat offa...,136,Thailand,"12,132",NaN,2016
58,160249,Other prepared or preserved meat and meat offa...,141,Viet Nam,"3,074",NaN,2016
59,160249,Other prepared or preserved meat and meat offa...,142,China,"451,556",NaN,2016
60,160249,Other prepared or preserved meat and meat offa...,143,Taiwan£¬China,"60,583",NaN,2016
61,160249,Other prepared or preserved meat and meat offa...,304,Germany,"65,252",NaN,2016
62,160249,Other prepared or preserved meat and meat offa...,307,Italy,"15,783",NaN,2016
63,160249,Other prepared or preserved meat and meat offa...,312,Spain,3,NaN,2016
64,160249,Other prepared or preserved meat and meat offa...,315,Austria,87,NaN,2016
65,160249,Other prepared or preserved meat and meat offa...,502,United States,"5,318",NaN,2016
66,20641,"Livers,frozen",302,Denmark,"18,983",NaN,2024
67,20641,"Livers,frozen",303,United Kingdom,"1,986",NaN,2024
68,20641,"Livers,frozen",312,Spain,"710,288",NaN,2024
69,20641,"Livers,frozen",318,Finland,"11,916",NaN,2024
70,20641,"Livers,frozen",412,Chile,"586,938",NaN,2024
71,20649,"Other edible offal of swine,frozen",301,Belgium,"16,811,153",NaN,2024
72,20649,"Other edible offal of swine,frozen",302,Denmark,"226,982,938",NaN,2024
73,20649,"Other edible offal of swine,frozen",303,United Kingdom,"104,037,137",NaN,2024
74,20649,"Other edible offal of swine,frozen",305,France,"181,953,727",NaN,2024
75,20649,"Other edible offal of swine,frozen",306,Ireland,"46,466,259",NaN,2024
76,20649,"Other edible offal of swine,frozen",309,Netherlands,"253,395,729",NaN,2024
77,20649,"Other edible offal of swine,frozen",311,Portugal,"3,398,723",NaN,2024
78,20649,"Other edible offal of swine,frozen",312,Spain,"564,756,094",NaN,2024
79,20649,"Other edible offal of swine,frozen",318,Finland,"17,465,497",NaN,2024
80,20649,"Other edible offal of swine,frozen",331,Switzerland,"9,225,881",NaN,2024
81,20649,"Other edible offal of swine,frozen",344,Russia,"36,402,023",NaN,2024
82,20649,"Other edible offal of swine,frozen",410,Brazil,"76,900,648",NaN,2024
83,20649,"Other edible offal of swine,frozen",412,Chile,"66,123,139",NaN,2024
84,20649,"Other edible offal of swine,frozen",429,Mexico,"192,858",NaN,2024
85,20649,"Other edible offal of swine,frozen",501,Canada,"220,549,725",NaN,2024
86,20649,"Other edible offal of swine,frozen",502,United States,"694,888,966",NaN,2024
87,160249,Other prepared or preserved meat and meat offa...,302,Denmark,"548,582",NaN,2024
88,160249,Other prepared or preserved meat and meat offa...,312,Spain,"93,110",NaN,2024
89,160249,Other prepared or preserved meat and meat offa...,502,United States,"44,879,849",NaN,2024
90,20641,NaN,312,Spain,"97,390",NaN,2018
91,20641,NaN,412,Chile,"120,331",NaN,2018
92,20649,NaN,301,Belgium,"16,352,299",NaN,2018
93,20649,NaN,302,Denmark,"203,848,120",NaN,2018
94,20649,NaN,303,United Kingdom,"31,981,052",NaN,2018
95,20649,NaN,304,Germany,"212,251,762",NaN,2018
96,20649,NaN,305,France,"108,818,712",NaN,2018
97,20649,NaN,306,Ireland,"31,126,828",NaN,2018
98,20649,NaN,309,Netherlands,"166,836,325",NaN,2018
99,20649,NaN,312,Spain,"184,317,710",NaN,2018
100,20649,NaN,318,Finland,"4,125,642",NaN,2018
101,20649,NaN,321,Hungary,"6,651,224",NaN,2018
102,20649,NaN,412,Chile,"39,201,611",NaN,2018
103,20649,NaN,429,Mexico,"1,530,962",NaN,2018
104,20649,NaN,501,Canada,"166,256,783",NaN,2018
105,20649,NaN,502,United States,"343,655,744",NaN,2018
106,160249,NaN,110,Hong Kong£¬China,52,NaN,2018
107,160249,NaN,116,Japan,"1,459",NaN,2018
108,160249,NaN,132,Singapore,648,NaN,2018
109,160249,NaN,133,Republic of Korea,3,NaN,2018
110,160249,NaN,142,China,"242,786",NaN,2018
111,160249,NaN,143,Taiwan£¬China,"1,412",NaN,2018
112,160249,NaN,302,Denmark,"691,694",NaN,2018
113,160249,NaN,304,Germany,482,NaN,2018
114,160249,NaN,305,France,"12,642",NaN,2018
115,160249,NaN,307,Italy,"49,351",NaN,2018
116,160249,NaN,358,Serbia,39,NaN,2018
117,160249,NaN,502,United States,"45,192",NaN,2018
118,160249,NaN,601,Australia,479,NaN,2018
119,20641,"Livers,frozen",302,Denmark,"955,017",NaN,2019
120,20641,"Livers,frozen",304,Germany,"20,426",NaN,2019
121,20641,"Livers,frozen",306,Ireland,"81,222",NaN,2019
122,20641,"Livers,frozen",309,Netherlands,"693,948",NaN,2019
123,20641,"Livers,frozen",312,Spain,"913,930",NaN,2019
124,20641,"Livers,frozen",412,Chile,"836,474",NaN,2019
125,20649,"Other edible offal of swine,frozen",302,Denmark,"254,904,091",NaN,2019
126,20649,"Other edible offal of swine,frozen",303,United Kingdom,"67,116,591",NaN,2019
127,20649,"Other edible offal of swine,frozen",304,Germany,"321,619,445",NaN,2019
128,20649,"Other edible offal of swine,frozen",305,France,"142,354,730",NaN,2019
129,20649,"Other edible offal of swine,frozen",306,Ireland,"46,985,885",NaN,2019
130,20649,"Other edible offal of swine,frozen",307,Italy,"285,554",NaN,2019
131,20649,"Other edible offal of swine,frozen",309,Netherlands,"229,420,650",NaN,2019
132,20649,"Other edible offal of swine,frozen",312,Spain,"300,335,153",NaN,2019
133,20649,"Other edible offal of swine,frozen",318,Finland,"9,957,681",NaN,2019
134,20649,"Other edible offal of swine,frozen",412,Chile,"57,526,534",NaN,2019
135,20649,"Other edible offal of swine,frozen",429,Mexico,"4,674,371",NaN,2019
136,20649,"Other edible offal of swine,frozen",501,Canada,"154,374,393",NaN,2019
137,20649,"Other edible offal of swine,frozen",502,United States,"273,964,688",NaN,2019
138,160249,"Other, including mixtures",116,Japan,"1,353",NaN,2019
139,160249,"Other, including mixtures",142,China,"42,377",NaN,2019
140,160249,"Other, including mixtures",302,Denmark,"2,820,946",NaN,2019
141,160249,"Other, including mixtures",304,Germany,"3,417",NaN,2019
142,160249,"Other, including mixtures",305,France,"53,581",NaN,2019
143,160249,"Other, including mixtures",307,Italy,"74,206",NaN,2019
144,160249,"Other, including mixtures",344,Russia,105,NaN,2019
145,160249,"Other, including mixtures",502,United States,"50,482",NaN,2019
146,20641,"Livers,frozen",305,France,"19,928",NaN,2022
147,20641,"Livers,frozen",412,Chile,"291,181",NaN,2022
148,20641,"Livers,frozen",501,Canada,458,NaN,2022
149,20649,"Other edible offal of swine,frozen",302,Denmark,"344,299,536",NaN,2022
150,20649,"Other edible offal of swine,frozen",303,United Kingdom,"113,238,500",NaN,2022
151,20649,"Other edible offal of swine,frozen",305,France,"218,287,180",NaN,2022
152,20649,"Other edible offal of swine,frozen",306,Ireland,"51,718,067",NaN,2022
153,20649,"Other edible offal of swine,frozen",307,Italy,"7,685,236",NaN,2022
154,20649,"Other edible offal of swine,frozen",309,Netherlands,"270,358,094",NaN,2022
155,20649,"Other edible offal of swine,frozen",311,Portugal,"3,970,727",NaN,2022
156,20649,"Other edible offal of swine,frozen",312,Spain,"611,906,271",NaN,2022
157,20649,"Other edible offal of swine,frozen",318,Finland,"18,610,263",NaN,2022
158,20649,"Other edible offal of swine,frozen",331,Switzerland,"10,178,561",NaN,2022
159,20649,"Other edible offal of swine,frozen",410,Brazil,"79,029,302",NaN,2022
160,20649,"Other edible offal of swine,frozen",412,Chile,"78,349,918",NaN,2022
161,20649,"Other edible offal of swine,frozen",415,Costa Rica,"192,931",NaN,2022
162,20649,"Other edible offal of swine,frozen",429,Mexico,"14,325,781",NaN,2022
163,20649,"Other edible offal of swine,frozen",501,Canada,"95,348,253",NaN,2022
164,20649,"Other edible offal of swine,frozen",502,United States,"772,907,790",NaN,2022
165,160249,Other prepared or preserved meat and meat offa...,142,China,"50,862",NaN,2022
166,160249,Other prepared or preserved meat and meat offa...,302,Denmark,"2,366,914",NaN,2022
167,160249,Other prepared or preserved meat and meat offa...,307,Italy,"125,060",NaN,2022
168,160249,Other prepared or preserved meat and meat offa...,312,Spain,"253,756",NaN,2022
169,20641,"Livers,frozen",305,France,"15,103",NaN,2023
170,20641,"Livers,frozen",412,Chile,"465,313",NaN,2023
171,20649,"Other edible offal of swine,frozen",302,Denmark,"267,190,269",NaN,2023
172,20649,"Other edible offal of swine,frozen",303,United Kingdom,"108,485,250",NaN,2023
173,20649,"Other edible offal of swine,frozen",305,France,"205,328,937",NaN,2023
174,20649,"Other edible offal of swine,frozen",306,Ireland,"49,775,575",NaN,2023
175,20649,"Other edible offal of swine,frozen",309,Netherlands,"291,696,483",NaN,2023
176,20649,"Other edible offal of swine,frozen",311,Portugal,"4,039,814",NaN,2023
177,20649,"Other edible offal of swine,frozen",312,Spain,"618,427,628",NaN,2023
178,20649,"Other edible offal of swine,frozen",318,Finland,"22,266,805",NaN,2023
179,20649,"Other edible offal of swine,frozen",331,Switzerland,"10,784,387",NaN,2023
180,20649,"Other edible offal of swine,frozen",410,Brazil,"78,790,723",NaN,2023
181,20649,"Other edible offal of swine,frozen",412,Chile,"81,585,528",NaN,2023
182,20649,"Other edible offal of swine,frozen",429,Mexico,"1,454,376",NaN,2023
183,20649,"Other edible offal of swine,frozen",501,Canada,"213,825,644",NaN,2023
184,20649,"Other edible offal of swine,frozen",502,United States,"786,254,442",NaN,2023
185,160249,Other prepared or preserved meat and meat offa...,142,China,61,NaN,2023
186,160249,Other prepared or preserved meat and meat offa...,302,Denmark,"1,898,133",NaN,2023
187,160249,Other prepared or preserved meat and meat offa...,312,Spain,"376,891",NaN,2023
188,160249,Other prepared or preserved meat and meat offa...,502,United States,"2,418,908",NaN,2023
189,20641,"Livers,frozen",302,Denmark,"599,318",NaN,2021
190,20641,"Livers,frozen",303,United Kingdom,"163,215",NaN,2021
191,20641,"Livers,frozen",305,France,"1,086,733",NaN,2021
192,20641,"Livers,frozen",306,Ireland,"413,797",NaN,2021
193,20641,"Livers,frozen",309,Netherlands,"1,443,268",NaN,2021
194,20641,"Livers,frozen",312,Spain,"7,797,583",NaN,2021
195,20641,"Livers,frozen",331,Switzerland,"3,996",NaN,2021
196,20641,"Livers,frozen",412,Chile,"1,817,078",NaN,2021
197,20641,"Livers,frozen",501,Canada,"351,869",NaN,2021
198,20649,"Other edible offal of swine,frozen",302,Denmark,"358,378,713",NaN,2021
199,20649,"Other edible offal of swine,frozen",303,United Kingdom,"105,768,775",NaN,2021
200,20649,"Other edible offal of swine,frozen",304,Germany,"1,252,695",NaN,2021
201,20649,"Other edible offal of swine,frozen",305,France,"225,611,609",NaN,2021
202,20649,"Other edible offal of swine,frozen",306,Ireland,"61,740,934",NaN,2021
203,20649,"Other edible offal of swine,frozen",307,Italy,"39,286,533",NaN,2021
204,20649,"Other edible offal of swine,frozen",309,Netherlands,"283,483,275",NaN,2021
205,20649,"Other edible offal of swine,frozen",311,Portugal,"2,218,997",NaN,2021
206,20649,"Other edible offal of swine,frozen",312,Spain,"698,505,872",NaN,2021
207,20649,"Other edible offal of swine,frozen",318,Finland,"17,969,710",NaN,2021
208,20649,"Other edible offal of swine,frozen",331,Switzerland,"8,388,222",NaN,2021
209,20649,"Other edible offal of swine,frozen",410,Brazil,"61,929,222",NaN,2021
210,20649,"Other edible offal of swine,frozen",412,Chile,"91,878,432",NaN,2021
211,20649,"Other edible offal of swine,frozen",415,Costa Rica,"179,159",NaN,2021
212,20649,"Other edible offal of swine,frozen",429,Mexico,"16,040,613",NaN,2021
213,20649,"Other edible offal of swine,frozen",501,Canada,"106,158,333",NaN,2021
214,20649,"Other edible offal of swine,frozen",502,United States,"739,350,900",NaN,2021
215,160249,"Other, including mixtures",136,Thailand,635,NaN,2021
216,160249,"Other, including mixtures",142,China,"55,688",NaN,2021
217,160249,"Other, including mixtures",302,Denmark,"1,579,968",NaN,2021
218,160249,"Other, including mixtures",305,France,"3,229",NaN,2021
219,160249,"Other, including mixtures",307,Italy,"250,398",NaN,2021
220,160249,"Other, including mixtures",312,Spain,"39,190",NaN,2021
221,20641,"Livers,frozen",302,Denmark,"1,537,931",NaN,2020
222,20641,"Livers,frozen",303,United Kingdom,"359,930",NaN,2020
223,20641,"Livers,frozen",304,Germany,"71,407",NaN,2020
224,20641,"Livers,frozen",305,France,"632,725",NaN,2020
225,20641,"Livers,frozen",306,Ireland,"808,260",NaN,2020
226,20641,"Livers,frozen",309,Netherlands,"2,390,000",NaN,2020
227,20641,"Livers,frozen",312,Spain,"10,864,353",NaN,2020
228,20641,"Livers,frozen",412,Chile,"2,915,313",NaN,2020
229,20641,"Livers,frozen",415,Costa Rica,"13,500",NaN,2020
230,20641,"Livers,frozen",501,Canada,"629,644",NaN,2020
231,20649,"Other edible offal of swine,frozen",302,Denmark,"295,496,604",NaN,2020
232,20649,"Other edible offal of swine,frozen",303,United Kingdom,"109,716,736",NaN,2020
233,20649,"Other edible offal of swine,frozen",304,Germany,"330,236,908",NaN,2020
234,20649,"Other edible offal of swine,frozen",305,France,"185,209,158",NaN,2020
235,20649,"Other edible offal of swine,frozen",306,Ireland,"49,210,379",NaN,2020
236,20649,"Other edible offal of swine,frozen",307,Italy,"26,809,841",NaN,2020
237,20649,"Other edible offal of swine,frozen",309,Netherlands,"231,182,253",NaN,2020
238,20649,"Other edible offal of swine,frozen",311,Portugal,"525,891",NaN,2020
239,20649,"Other edible offal of swine,frozen",312,Spain,"539,669,726",NaN,2020
240,20649,"Other edible offal of swine,frozen",318,Finland,"13,941,368",NaN,2020
241,20649,"Other edible offal of swine,frozen",331,Switzerland,"3,103,810",NaN,2020
242,20649,"Other edible offal of swine,frozen",410,Brazil,"31,753,790",NaN,2020
243,20649,"Other edible offal of swine,frozen",412,Chile,"87,519,249",NaN,2020
244,20649,"Other edible offal of swine,frozen",415,Costa Rica,"166,909",NaN,2020
245,20649,"Other edible offal of swine,frozen",429,Mexico,"10,446,715",NaN,2020
246,20649,"Other edible offal of swine,frozen",501,Canada,"202,222,842",NaN,2020
247,20649,"Other edible offal of swine,frozen",502,United States,"506,248,785",NaN,2020
248,160249,"Other, including mixtures",116,Japan,430,NaN,2020
249,160249,"Other, including mixtures",133,Republic of Korea,"2,287",NaN,2020
250,160249,"Other, including mixtures",136,Thailand,30,NaN,2020
251,160249,"Other, including mixtures",302,Denmark,"4,660,661",NaN,2020
252,160249,"Other, including mixtures",305,France,"67,644",NaN,2020
253,160249,"Other, including mixtures",307,Italy,"127,608",NaN,2020
254,160249,"Other, including mixtures",344,Russia,"2,134",NaN,2020
255,160249,"Other, including mixtures",445,Venezuela,143,NaN,2020
256,160249,"Other, including mixtures",502,United States,"383,987",NaN,2020

In [235]:
combined_df['US dollar'] = (
    combined_df['US dollar']
    .astype(str)
    .str.replace(',', '', regex=True)
    .astype(float)
)

country_year_totals = (
    combined_df
    .groupby(['year', 'Trading partner'], as_index=False)
    ['US dollar']
    .sum()
    .sort_values(['year', 'US dollar'], ascending=[True, False])
)

country_year_totals['US dollar (billions)'] = (
    country_year_totals['US dollar'] / 1_000_000_000
).round(3)

for year in country_year_totals['year'].unique():
    yearly_data = country_year_totals[country_year_totals['year'] == year].head()

In [236]:
country_year_totals

     year    Trading partner    US dollar  US dollar (billions)
19   2016      United States  936816463.0                 0.937
7    2016            Germany  360720934.0                 0.361
5    2016            Denmark  337813137.0                 0.338
2    2016             Canada  200275012.0                 0.200
15   2016              Spain  182207657.0                 0.182
13   2016        Netherlands  156136718.0                 0.156
6    2016             France  116297163.0                 0.116
3    2016              Chile   44101092.0                 0.044
18   2016     United Kingdom   37308744.0                 0.037
10   2016            Ireland   35284358.0                 0.035
1    2016            Belgium   26790801.0                 0.027
9    2016            Hungary   18377455.0                 0.018
14   2016            Romania    4485065.0                 0.004
4    2016              China     451556.0                 0.000
12   2016             Mexico      89570.0                 0.000
16   2016      Taiwan£¬China      60583.0                 0.000
11   2016              Italy      15783.0                 0.000
17   2016           Thailand      12132.0                 0.000
20   2016           Viet Nam       3074.0                 0.000
8    2016   Hong Kong£¬China        831.0                 0.000
0    2016            Austria         87.0                 0.000
42   2017      United States  873810968.0                 0.874
25   2017            Denmark  219926307.0                 0.220
28   2017            Germany  213418028.0                 0.213
38   2017              Spain  198370005.0                 0.198
22   2017             Canada  183969123.0                 0.184
34   2017        Netherlands  154377740.0                 0.154
27   2017             France  114280112.0                 0.114
23   2017              Chile   37486297.0                 0.037
30   2017            Ireland   32371683.0                 0.032
41   2017     United Kingdom   31029421.0                 0.031
21   2017            Belgium   25579786.0                 0.026
29   2017            Hungary   18168581.0                 0.018
37   2017            Romania    7439128.0                 0.007
26   2017            Finland    1825322.0                 0.002
33   2017             Mexico    1110387.0                 0.001
24   2017              China     937027.0                 0.001
31   2017              Italy      38642.0                 0.000
39   2017      Taiwan£¬China       5170.0                 0.000
40   2017           Thailand       2065.0                 0.000
36   2017  Republic of Korea        918.0                 0.000
32   2017              Japan         54.0                 0.000
35   2017    North Macedonia          1.0                 0.000
65   2018      United States  343700936.0                 0.344
51   2018            Germany  212252244.0                 0.212
48   2018            Denmark  204539814.0                 0.205
62   2018              Spain  184415100.0                 0.184
58   2018        Netherlands  166836325.0                 0.167
45   2018             Canada  166256783.0                 0.166
50   2018             France  108831354.0                 0.109
46   2018              Chile   39321942.0                 0.039
64   2018     United Kingdom   31981052.0                 0.032
54   2018            Ireland   31126828.0                 0.031
44   2018            Belgium   16352299.0                 0.016
53   2018            Hungary    6651224.0                 0.007
49   2018            Finland    4125642.0                 0.004
57   2018             Mexico    1530962.0                 0.002
47   2018              China     242786.0                 0.000
55   2018              Italy      49351.0                 0.000
56   2018              Japan       1459.0                 0.000
63   2018      Taiwan£¬China       1412.0                 0.000
61   2018          Singapore        648.0                 0.000
43   2018          Australia        479.0                 0.000
52   2018   Hong Kong£¬China         52.0                 0.000
60   2018             Serbia         39.0                 0.000
59   2018  Republic of Korea          3.0                 0.000
72   2019            Germany  321643288.0                 0.322
79   2019              Spain  301249083.0                 0.301
81   2019      United States  274015170.0                 0.274
69   2019            Denmark  258680054.0                 0.259
77   2019        Netherlands  230114598.0                 0.230
66   2019             Canada  154374393.0                 0.154
71   2019             France  142408311.0                 0.142
80   2019     United Kingdom   67116591.0                 0.067
67   2019              Chile   58363008.0                 0.058
73   2019            Ireland   47067107.0                 0.047
70   2019            Finland    9957681.0                 0.010
76   2019             Mexico    4674371.0                 0.005
74   2019              Italy     359760.0                 0.000
68   2019              China      42377.0                 0.000
75   2019              Japan       1353.0                 0.000
78   2019             Russia        105.0                 0.000
98   2020              Spain  550534079.0                 0.551
102  2020      United States  506632772.0                 0.507
89   2020            Germany  330308315.0                 0.330
86   2020            Denmark  301695196.0                 0.302
94   2020        Netherlands  233572253.0                 0.234
83   2020             Canada  202852486.0                 0.203
88   2020             France  185909527.0                 0.186
101  2020     United Kingdom  110076666.0                 0.110
84   2020              Chile   90434562.0                 0.090
90   2020            Ireland   50018639.0                 0.050
82   2020             Brazil   31753790.0                 0.032
91   2020              Italy   26937449.0                 0.027
87   2020            Finland   13941368.0                 0.014
93   2020             Mexico   10446715.0                 0.010
99   2020        Switzerland    3103810.0                 0.003
95   2020           Portugal     525891.0                 0.001
85   2020         Costa Rica     180409.0                 0.000
96   2020  Republic of Korea       2287.0                 0.000
97   2020             Russia       2134.0                 0.000
92   2020              Japan        430.0                 0.000
103  2020          Venezuela        143.0                 0.000
100  2020           Thailand         30.0                 0.000
122  2021      United States  739350900.0                 0.739
118  2021              Spain  706342645.0                 0.706
109  2021            Denmark  360557999.0                 0.361
116  2021        Netherlands  284926543.0                 0.285
111  2021             France  226701571.0                 0.227
105  2021             Canada  106510202.0                 0.107
121  2021     United Kingdom  105931990.0                 0.106
106  2021              Chile   93695510.0                 0.094
113  2021            Ireland   62154731.0                 0.062
104  2021             Brazil   61929222.0                 0.062
114  2021              Italy   39536931.0                 0.040
110  2021            Finland   17969710.0                 0.018
115  2021             Mexico   16040613.0                 0.016
119  2021        Switzerland    8392218.0                 0.008
117  2021           Portugal    2218997.0                 0.002
112  2021            Germany    1252695.0                 0.001
108  2021         Costa Rica     179159.0                 0.000
107  2021              China      55688.0                 0.000
120  2021           Thailand        635.0                 0.000
139  2022      United States  772907790.0                 0.773
136  2022              Spain  612160027.0                 0.612
128  2022            Denmark  346666450.0                 0.347
134  2022        Netherlands  270358094.0                 0.270
130  2022             France  218307108.0                 0.218
138  2022     United Kingdom  113238500.0                 0.113
124  2022             Canada   95348711.0                 0.095
123  2022             Brazil   79029302.0                 0.079
125  2022              Chile   78641099.0                 0.079
131  2022            Ireland   51718067.0                 0.052
129  2022            Finland   18610263.0                 0.019
133  2022             Mexico   14325781.0                 0.014
137  2022        Switzerland   10178561.0                 0.010
132  2022              Italy    7810296.0                 0.008
135  2022           Portugal    3970727.0                 0.004
127  2022         Costa Rica     192931.0                 0.000
126  2022              China      50862.0                 0.000
154  2023      United States  788673350.0                 0.789
151  2023              Spain  618804519.0                 0.619
149  2023        Netherlands  291696483.0                 0.292
144  2023            Denmark  269088402.0                 0.269
141  2023             Canada  213825644.0                 0.214
146  2023             France  205344040.0                 0.205
153  2023     United Kingdom  108485250.0                 0.108
142  2023              Chile   82050841.0                 0.082
140  2023             Brazil   78790723.0                 0.079
147  2023            Ireland   49775575.0                 0.050
145  2023            Finland   22266805.0                 0.022
152  2023        Switzerland   10784387.0                 0.011
150  2023           Portugal    4039814.0                 0.004
148  2023             Mexico    1454376.0                 0.001
143  2023              China         61.0                 0.000
170  2024      United States  739768815.0                 0.740
167  2024              Spain  565559492.0                 0.566
164  2024        Netherlands  253395729.0                 0.253
159  2024            Denmark  227550503.0                 0.228
157  2024             Canada  220549725.0                 0.221
161  2024             France  181953727.0                 0.182
169  2024     United Kingdom  104039123.0                 0.104
156  2024             Brazil   76900648.0                 0.077
158  2024              Chile   66710077.0                 0.067
162  2024            Ireland   46466259.0                 0.046
166  2024             Russia   36402023.0                 0.036
160  2024            Finland   17477413.0                 0.017
155  2024            Belgium   16811153.0                 0.017
168  2024        Switzerland    9225881.0                 0.009
165  2024           Portugal    3398723.0                 0.003
163  2024             Mexico     192858.0                 0.000

In [245]:
# Pivot the table to get years as columns
wide_format_df = (
    country_year_totals
    .pivot(index='Trading partner', 
           columns='year', 
           values='US dollar (billions)')
    .reset_index()
)

# Reorder columns chronologically
year_columns = sorted([col for col in wide_format_df.columns if isinstance(col, int)])
wide_format_df = wide_format_df[['Trading partner'] + year_columns]

# Round to 2 decimal places for cleaner display
wide_format_df[year_columns] = wide_format_df[year_columns].round(2)

# Rename year columns to strings if needed
wide_format_df.columns = ['Trading partner'] + [str(year) for year in year_columns]

# Sort by 2024 values (highest first)
wide_format_df = wide_format_df.sort_values('2024', ascending=False)

wide_format_df.head()

   Trading partner  2016  2017  2018  2019  2020  2021  2022  2023  2024
31   United States  0.94  0.87  0.34  0.27  0.51  0.74  0.77  0.79  0.74
26           Spain  0.18  0.20  0.18  0.30  0.55  0.71  0.61  0.62  0.57
18     Netherlands  0.16  0.15  0.17  0.23  0.23  0.28  0.27  0.29  0.25
8          Denmark  0.34  0.22  0.20  0.26  0.30  0.36  0.35  0.27  0.23
4           Canada  0.20  0.18  0.17  0.15  0.20  0.11  0.10  0.21  0.22

In [249]:
wide_format_df.to_csv('offals_long.csv', index=False)

In [329]:
yearly_exports = country_year_totals.groupby(['year', 'Trading partner'])['US dollar'].sum().reset_index()

# Get top 5 exporters per year
top_by_year = yearly_exports.groupby('year').apply(
    lambda x: x.nlargest(5, 'US dollar')
).reset_index(drop=True)

/var/folders/zz/2b8md6f924779tdhfsf8zvqm0000gn/T/ipykernel_5589/3944700646.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top_by_year = yearly_exports.groupby('year').apply(

In [330]:
top_by_year

    year Trading partner    US dollar
0   2016   United States  936816463.0
1   2016         Germany  360720934.0
2   2016         Denmark  337813137.0
3   2016          Canada  200275012.0
4   2016           Spain  182207657.0
5   2017   United States  873810968.0
6   2017         Denmark  219926307.0
7   2017         Germany  213418028.0
8   2017           Spain  198370005.0
9   2017          Canada  183969123.0
10  2018   United States  343700936.0
11  2018         Germany  212252244.0
12  2018         Denmark  204539814.0
13  2018           Spain  184415100.0
14  2018     Netherlands  166836325.0
15  2019         Germany  321643288.0
16  2019           Spain  301249083.0
17  2019   United States  274015170.0
18  2019         Denmark  258680054.0
19  2019     Netherlands  230114598.0
20  2020           Spain  550534079.0
21  2020   United States  506632772.0
22  2020         Germany  330308315.0
23  2020         Denmark  301695196.0
24  2020     Netherlands  233572253.0
25  2021   United States  739350900.0
26  2021           Spain  706342645.0
27  2021         Denmark  360557999.0
28  2021     Netherlands  284926543.0
29  2021          France  226701571.0
30  2022   United States  772907790.0
31  2022           Spain  612160027.0
32  2022         Denmark  346666450.0
33  2022     Netherlands  270358094.0
34  2022          France  218307108.0
35  2023   United States  788673350.0
36  2023           Spain  618804519.0
37  2023     Netherlands  291696483.0
38  2023         Denmark  269088402.0
39  2023          Canada  213825644.0
40  2024   United States  739768815.0
41  2024           Spain  565559492.0
42  2024     Netherlands  253395729.0
43  2024         Denmark  227550503.0
44  2024          Canada  220549725.0

In [336]:
yearly_exports['total_per_year'] = yearly_exports.groupby('year')['US dollar'].transform('sum')
yearly_exports['market_share'] = (yearly_exports['US dollar'] / yearly_exports['total_per_year']) * 100

# Focus on key countries (e.g., US, Germany, Brazil)
key_countries = ['United States', 'Canada', 'Netherlands', 'Spain', 'Denmark']
share_trends = yearly_exports[yearly_exports['Trading partner'].isin(key_countries)]

# Pivot for visualization
share_pivot = share_trends.pivot(index='year', columns='Trading partner', values='market_share')

In [337]:
share_pivot

Trading partner     Canada    Denmark  Netherlands      Spain  United States
year
2016              8.150378  13.747620     6.354129   7.415110      38.124617
2017              8.701814  10.402604     7.302130   9.382982      41.331613
2018             10.950779  13.472355    10.988952  12.146807      22.638433
2019              8.255018  13.832661    12.305151  16.108997      14.652691
2020              7.657906  11.389328     8.817611  20.783271      19.125948
2021              3.758634  12.723714    10.054760  24.926093      26.090920
2022              3.539937  12.870413    10.037373  22.727185      28.695141
2023              7.789413   9.802570    10.626155  22.542311      28.730429
2024              8.593732   8.866518     9.873578  22.037057      28.825132